### ISSUE TITLE
Invalid prop `children` of type `array` supplied to `UAProvider`

### ISSUE THREAD

**Issue by xdidx** [CianOShea/IndieLink#3]
Failed prop type: Invalid prop 'children' of type 'array' supplied to 'UAProvider', expected a single ReactElement

In index.js line 76 

I think that a simple div can wrap elements and fix the issue, like in [generic usage documentation](https://github.com/quentin-sommer/react-useragent#generic-usage ), but i'm not sure

**Comment by CianOShea** [comment]
This was fixed in latest commit
